@startuml
[*] --> pipewiresrc
pipewiresrc: Capture video from PipeWire
pipewiresrc --> videorate
videorate: Make framerate constant
videorate --> videoconvert
videoconvert: Convert video format
videoconvert --> timeoverlay
timeoverlay: Debug time in video
timeoverlay --> vaapipostproc
vaapipostproc: Convert video to VAAPI format
vaapipostproc --> vaapih264enc
vaapih264enc: Hardware H.264 encoding
vaapih264enc --> h264parse
h264parse: Parse H.264 stream
h264parse --> mpegtsmux
mpegtsmux: Mux into MPEG-TS
mpegtsmux --> rtmp2tpay
rtmp2tpay: RTP payloader for RTMP
rtmp2tpay --> queue
queue: Buffering queue
queue --> appsink
appsink: Output to application sink
appsink --> [*]
@enduml
