@startuml
top to bottom direction
pipewiresrc: Capture video\nfrom PipeWire
src_queue: Queue (leaky=downstream)
videorate: Make framerate constant
videoconvert: Convert video format
timeoverlay: Debug time in video
preprocess: vaapipostproc\n(or identity fallback)
encoder: vaapih264enc\n(or x264enc fallback)
h264parse: Parse H.264 stream\n(config-interval=1)
rtph264pay: RTP H.264 payloader\n(pt=96, mtu configurable)
payload_queue: Buffering queue
appsink: Output to application sink
[*] -right-> pipewiresrc
pipewiresrc -right-> src_queue
src_queue -right-> videorate
videorate -down-> videoconvert
videoconvert -left-> timeoverlay
timeoverlay -left-> preprocess
preprocess -down-> encoder
encoder -right-> h264parse
h264parse -right-> rtph264pay
rtph264pay -down-> payload_queue
payload_queue -left-> appsink
appsink -left-> [*]
@enduml
