@startuml
top to bottom direction
appsrc: Input from application memory\n(application/x-rtp, H264, pt=96)
rtpjitterbuffer: Reorder RTP packets\n(latency=5000)
h264parse: Parse H.264 stream
rtph264depay: RTP H.264 depayloader
decoder: vaapih264dec\n(or v4l2h264dec/avdec_h264 fallback)
postproc: vaapipostproc\n(optional)
videoconvert: Convert video format
dec_queue: Buffering queue
autovideosink: Output to screen
[*] -right-> appsrc
appsrc -right-> rtpjitterbuffer
rtpjitterbuffer -right-> rtph264depay
rtph264depay -down-> h264parse
h264parse -left-> decoder
decoder -left-> postproc
postproc -down-> videoconvert
videoconvert -right-> dec_queue
dec_queue -right-> autovideosink
autovideosink -right-> [*]
@enduml
